### ISSUE TITLE
Implement AIP-11 Support

### ISSUE THREAD

**Issue by sleepdefic1t** [ArkEcosystem/ledger-transport#10]
Implement Ledger-Transport sending payloads in the official [AIP-11](https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-11.md) Serialization schemes.

**Comment by alexbarnsley** [comment]
I think this issue is better off in the ledger repo. The bulk of the changes will be required there as per your statement `This Ledger-Transport scheme is also used Ledger-side at Tx deserialization`. 

IMO this issue is overly complicated/wordy, especially when C is included.

**Comment by sleepdefic1t** [comment]
I disagree.

The HW side changes are almost complete.

All we need is for this JS package is to send payloads using the official scheme at a minimum.

The big scary “C” examples were only to illustrate that the payload is incorrectly encoded.

I can edit this issue or make another issue that’s easier to understand and doesn’t use C as an example, but I’d still say a request for changes in the Transport package should be in the Transport repo.

**Comment by alexbarnsley** [comment]
I'm happy for it to remain open (hence why I didn't close it). It needs editing to remove the "big scary C", because this is a JS repo - either use JS, pseudo-code or English. Also, terminology such as "serde" doesn't make sense to those who don't know them, so you should avoid using short-hand phrases in this sort of environment.

**Comment by sleepdefic1t** [comment]
updated 👍

**Comment by alexbarnsley** [comment]
thanks 👌
